[server]
port=8501
maxUploadSize = 200
maxMessageSize = 200
headless=true
fileWatcherType="none"

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[logger]
level="info"
messageFormat = "%(asctime)s %(message)s"

[theme]
base="light"
primaryColor="#0059FF"
secondaryBackgroundColor="#ebecf1"
textColor="#000000"
font="sans serif"
